//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NeuroAttention {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NeuroAttention.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap appstore_de {
            get {
                object obj = ResourceManager.GetObject("appstore_de", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap appstore_en {
            get {
                object obj = ResourceManager.GetObject("appstore_en", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap appstore_tr {
            get {
                object obj = ResourceManager.GetObject("appstore_tr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to im_car\\app_storetr.png.
        /// </summary>
        internal static string btn_appstore {
            get {
                return ResourceManager.GetString("btn_appstore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YAZILIM GÜNCELLEMESİ.
        /// </summary>
        internal static string btn_checkupdate {
            get {
                return ResourceManager.GetString("btn_checkupdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oturum açamıyor musun?.
        /// </summary>
        internal static string btn_forgotpassword {
            get {
                return ResourceManager.GetString("btn_forgotpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to im_car\\google-play-badge.png.
        /// </summary>
        internal static string btn_googleplay {
            get {
                return ResourceManager.GetString("btn_googleplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KULLANICI SÖZLEŞMESİ.
        /// </summary>
        internal static string btn_kullanimsozlesmesi {
            get {
                return ResourceManager.GetString("btn_kullanimsozlesmesi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Türkçe (TR).
        /// </summary>
        internal static string btn_language {
            get {
                return ResourceManager.GetString("btn_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to false.
        /// </summary>
        internal static string btn_logindisabled {
            get {
                return ResourceManager.GetString("btn_logindisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daha fazla ayrıntı.
        /// </summary>
        internal static string btn_moredetails {
            get {
                return ResourceManager.GetString("btn_moredetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hesap oluştur.
        /// </summary>
        internal static string btn_register {
            get {
                return ResourceManager.GetString("btn_register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTURUMU AÇIK TUT.
        /// </summary>
        internal static string btn_session {
            get {
                return ResourceManager.GetString("btn_session", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Türkçe.
        /// </summary>
        internal static string cbox_language {
            get {
                return ResourceManager.GetString("cbox_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TR NATRO - db60.
        /// </summary>
        internal static string cbox_server {
            get {
                return ResourceManager.GetString("cbox_server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap googleplay_de {
            get {
                object obj = ResourceManager.GetObject("googleplay_de", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap googleplay_tr {
            get {
                object obj = ResourceManager.GetObject("googleplay_tr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UYGULAMA DİLİ.
        /// </summary>
        internal static string lbl_applanguage {
            get {
                return ResourceManager.GetString("lbl_applanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MEVCUT SÜRÜM.
        /// </summary>
        internal static string lbl_currentversion {
            get {
                return ResourceManager.GetString("lbl_currentversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AYARLAR.
        /// </summary>
        internal static string lbl_settings {
            get {
                return ResourceManager.GetString("lbl_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTURUM AÇ.
        /// </summary>
        internal static string lbl_signin {
            get {
                return ResourceManager.GetString("lbl_signin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SERVER / DİL.
        /// </summary>
        internal static string lbl_title {
            get {
                return ResourceManager.GetString("lbl_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ŞİFRE.
        /// </summary>
        internal static string txt_password {
            get {
                return ResourceManager.GetString("txt_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KULLANICI ADI.
        /// </summary>
        internal static string txt_username {
            get {
                return ResourceManager.GetString("txt_username", resourceCulture);
            }
        }
    }
}
